function gradual_color(x)
xgrid = -2:0.01:2;
ygrid = -2:0.01:2;
[X,Y] = meshgrid(xgrid,ygrid);

z = ones([1,length(X(:,x))]);

col = gen_col(x/length(xgrid),z);
test(:,1,:) = col(:,:);
test(:,2,:) = col(:,:);
h = surface(...
  'XData',[X(:,x) X(:,x)],...
  'YData',[Y(:,x) Y(:,x)],...
  'ZData',[z(:) z(:)],...
  'CData',test,...
  'FaceColor','none',...
  'EdgeColor','flat',...
  'Marker','none', ...
  'LineWidth',2);
