function gradual_color(fi,x)
figure(fi);
xgrid = -0.5*pi:0.005*pi:0.5*pi;
ygrid = -2:0.01:2;
[X,Y] = meshgrid(xgrid,ygrid);

z = ones([1,length(X(:,x))]);

col = gen_col(x/length(xgrid),z);
test(:,1,:) = col(:,:);
test(:,2,:) = col(:,:);
subplot(2,1,1)
h = surface(...
  'XData',[X(:,x) X(:,x)],...
  'YData',[Y(:,x) Y(:,x)],...
  'ZData',[z(:) z(:)],...
  'CData',test,...
  'FaceColor','none',...
  'EdgeColor','flat',...
  'Marker','none', ...
  'LineWidth',2);

Z = X(:,x)+1i*Y(:,x);
tz = sin(Z).^6;
subplot(2,1,2)

h = surface(...
  'XData',[real(tz) real(tz)],...
  'YData',[imag(tz) imag(tz)],...
  'ZData',[z(:) z(:)],...
  'CData',test,...
  'FaceColor','none',...
  'EdgeColor','flat',...
  'Marker','none', ...
  'LineWidth',2);
